### ISSUE TITLE
Can this work outside `main` package?

### ISSUE THREAD

**Issue by russoj88** [steverusso/goclap#41]
@steverusso I started making a [Go Example](https://go.dev/blog/examples) test [here](https://github.com/russoj88/goclap/tree/using_go_example_tests), but goclap doesn't seem to generate the right code if it's outside the main package.

Is this something it could support? I think having testable example would be beneficial for the project!

**Comment by steverusso** [comment]
This raises two good points:
1. goclap as it stands will panic when used on any package other than `main` since I naively hardcoded the package name.
2. I think tests would be beneficial, and testable examples probably can't hurt. I'll investigate that branch a little further and start making whichever few adjustments are necessary here.

**Comment by steverusso** [comment]
With https://github.com/steverusso/goclap/commit/4c3916fdee43a524ea96971e4495adae5ca08cfd, it won't panic for a package other than `main` :heavy_check_mark:
